### ISSUE TITLE
Android issues (no `onProgress`, can't save audio)

### ISSUE THREAD

**Issue by cooperka** [jsierles/react-native-audio#149]
The example app on Android becomes slow after pressing "RECORD", never sends any `onProgress` or `onFinished` callbacks, then doesn't save the audio after you press "STOP". I'm having the exact same issues on my full app.

An exception is being thrown when calling `recorder.stop()`, previously [causing a crash](https://github.com/jsierles/react-native-audio/pull/148) but now it's just swallowed: `E/MediaRecorder: stop failed: -1007`. I'm sure this is related, but it seems to be a symptom rather than the cause. According to the [MediaRecorder docs](https://developer.android.com/reference/android/media/MediaRecorder.html#stop()):

> A RuntimeException is intentionally thrown to the application if no valid audio/video data has been received when stop() is called.

On my real device, instead of this exception, I'm getting `W/MediaRecorder: mediarecorder went away with unhandled events`, and `onFinished` is still never called.

I've tested on multiple Android versions (including 4.4 and 6.0) at multiple points in time (including bfd865cb561263569a53d632debc80bd4f3ff5e8, c0b4ad13884f46bd7bbfa3c42148827a69ca1542, and 2f46794437074847672f48b1388727aa73a12e3e) on both the emulator and a real device, and the issue is always the same for me. No callbacks are ever called.

Based on the comments at https://github.com/jsierles/react-native-audio/pull/139 it seems like @q6112345 and @Slooowpoke got it working... can you comment on whether it's ever worked for you on Android, and what steps you needed to take?

**Comment by Slooowpoke** [comment]
Yup it does work for Android, however for a time it didn't (around the time of RN 0.35) I switched phones and Android versions from (I think 4.4? or 4.0?). I've been testing on Android 6.0 recently and it works for the most part, I receive a stop failed error if the recorder doesn't pick up on any sound but I think the error is -2. I've only tried it for Android on physical devices.

As for the onProgress reporting, I have a comment in another thread: https://github.com/jsierles/react-native-audio/issues/111#issuecomment-272831926

I'll be able to help a bit more tomorrow since all my development has been at work and I don't have access here. Hope some of that was a little useful.

**Comment by cooperka** [comment]
@Slooowpoke thanks for the link, that's really helpful. I'm thinking now that the emulator may just be incapable of recording audio, hence the `RuntimeException`. I'll try your way of listening for events and update here if I find a better fix.
