### ISSUE TITLE
Find the recorderd file and remove the recorded audio file

### ISSUE THREAD

**Issue by henrykapostel** [jsierles/react-native-audio#159]
I have implemented this module to record microphone, it works fine. But I have got some problems.
- Please let me know how to find the recorded file on devices.
The recorded filepath is returned as like this - /data/user/0/com.Example/files/test.aac and I couldn't find this path on my device(Android exactly).
- Please let me know if there is any functionality to remove the recorded audio file.
I am trying to make recording audio files and need to delete these owing to lack of disk size.

**Comment by soutot** [comment]
I was also wondering how to find the files. Can someone give us a hint, please?

**Comment by bakr-baroudi** [comment]
+1

**Comment by chmac** [comment]
On android you cannot access `/data` without being root. If your device is not rooted you can use `adb` to make a backup of the app and then you can extract the backup something along these lines:

    adb backup -f app.ab com.app.id.whatever
    dd if=app.ab bs=24 skip=1 | python -c "import zlib,sys;sys.stdout.write(zlib.decompress(sys.stdin.read()))" > app.tar

There is an option to use `openssl` instead of `python` on other systems, but this one worked for me on macOS Sierra. Then you can untar the `app.tar` file. You can also pipe to `tar -xf -` instead of piping to a file.

**Comment by RakanNimer** [comment]
You can provide the path to which you want to write your audio file and then retrieve it via react-native-fs or play it with react-native-sound.

Please check the example [here](https://github.com/jsierles/react-native-audio/blob/master/AudioExample/AudioExample.js#L23).

If you could also provide a link to a repo that reproduces the issue it would be very helpful to help us help you debug the issue.

Cheers

**Comment by bakr-baroudi** [comment]
Thanks. I used adb shell to get the file, it works!
