### ISSUE TITLE
AMR For IOS

### ISSUE THREAD

**Issue by CarGuo** [jsierles/react-native-audio#162]
hello，i use in iOS amr like this 
![wechatimg1](https://cloud.githubusercontent.com/assets/10770362/23825157/5a90f1ec-06bf-11e7-872a-fed625e3d857.jpeg)

but got error like this
![wechatimg2](https://cloud.githubusercontent.com/assets/10770362/23825166/942ed586-06bf-11e7-82be-504e6acd9bfc.jpeg)
what can i do??

**Comment by CarGuo** [comment]
AVAudioRecorder not support amr ？

**Comment by jsierles** [comment]
Did you try `samr`? Here is looked like 'AMR Narrowband' may be supported: https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/CoreAudioOverview/SupportedAudioFormatsMacOSX/SupportedAudioFormatsMacOSX.html

**Comment by yangsamuellu** [comment]
i got the error like CarGuo.   @jsierles  how to fix this issure?

**Comment by simonasdev** [comment]
I have used

**Comment by simonasdev** [comment]
I have used this
```javascript
Recorder.prepareRecordingAtPath(AudioUtils.DocumentDirectoryPath + '/voice-message.caf', {
      SampleRate: 8000,
      Channels: 1,
      AudioQuality: "Low",
      AudioEncoding: "samr"
})
```
since it appears that the only file format, which supports `samr` (AMR narrowband) is `caf`. Though I'm not sure if the file being recorded is actually a proper AMR, since ffmpeg reports that it is `adpcm_ima_qt`

**Comment by simonasdev** [comment]
Current implementation does not allow usage of `samr`. Code above actually records in `kAudioFormatAppleIMA4` format, since that is the default. But the point is that `samr` is in fact the same `kAudioFormatAMR`, which is unsupported at all for recording. If you would try to write a `.caf` file with `AudioEncoding: 'amr'` you would get `error: The operation couldn’t be completed. (OSStatus error 1718449215.)`, which translates to `kAudioFormatUnsupportedDataFormatError`. 
The audio recording formats supported in iOS are the following (https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/MultimediaPG/UsingAudio/UsingAudio.html):
AAC (on supported devices only)
ALAC (Apple Lossless)
iLBC (internet Low Bitrate Codec, for speech)
IMA4 (IMA/ADPCM)
linear PCM
µ-law and a-law

So `amr` is not supported for recording and there is no reason to have code giving false hope that it might work. IMO it should be removed to not confuse people
