### ISSUE TITLE
FEATURE REQUEST: Record audio to mp3.

### ISSUE THREAD

**Issue by wootwoot1234** [jsierles/react-native-audio#17]
Is it possible to record audio to an mp3 file?  It would save a ton of space for apps that record a lot of audio (like mine).  :)

**Comment by jsierles** [comment]
Unfortunately, there is no built-in way to convert to mp3, which is a prioprietary format. You could try lower audio quality settings, or using one of the AAC conversion libraries to convert afterwards. Of course, both of these options require modifying the native code.

In the near future I will be adding the ability to control au

**Comment by wootwoot1234** [comment]
I'm not very good with objective c but I might try adding a feature to encode the audio after it's recorded.  I edited this plugin for cordova a while back for it to do what I needed.  Would you be willing to add an encoding method to your code?  I think it would be pretty easy to copy and paste this code for someone who knows objective c?

https://github.com/wootwoot1234/cordova-audio-encode/blob/master/src/ios/AudioEncode.m

**Comment by jsierles** [comment]
I looked into this a bit more, and it turns out I was wrong: you can in fact record to mp3, as well as m4a and other formats described here:

https://developer.apple.com/library/ios/documentation/MusicAudio/Reference/CoreAudioDataTypesRef/index.html#//apple_ref/doc/constant_group/Audio_Data_Format_Identifiers

You'd have to add one line for setting the format here:

https://github.com/jsierles/react-native-audio/blob/master/ios/AudioRecorderManager.m#L93

I can get around to adding this feature, but right now and really busy. I hope to get back to it soon.

**Comment by alchibaucha** [comment]
@jsierles Is the feature to save on mp3 format available? It would be awesome :)

**Comment by FredBBS** [comment]
@jsierles Same need here :) MP3 would be great!
