### ISSUE TITLE
android cant play ios aac file

### ISSUE THREAD

**Issue by zmGitHub** [jsierles/react-native-audio#192]
i record aac file on ios and upload to server, when i play the file from server, just nothing

**Comment by yp08107** [comment]
1

**Comment by rmsouza** [comment]
Hey guys, I have the same issue. Did you solve it?

**Comment by jsierles** [comment]
See https://github.com/jsierles/react-native-audio/issues/161

**Comment by saplf** [comment]
For those who have the same issue with another possible bug. What needs to be emphasized is that it happens to the file recorded in iOS instead of Android.

I thought it was unnecessary to pay attention to the file suffix of the audio's output path since the format information is recorded in the file header. I just specified the `acc` encoding:

```javascript
audioOption = {
  // ...
  AudioEncoding: 'aac',
}
AudioRecorder.prepareRecordingAtPath('/path/without/suffix', audioOption)
```

```objc
_audioEncoding = [NSNumber numberWithInt:kAudioFormatMPEG4AAC];
```

However, `acc` encoding has a lot of formats. If the given path doesn't have a suffix, iOS will produce the audio with format `CAF` which cannot be identified by Android and browser. So, the code should be:

```javascript
AudioRecorder.prepareRecordingAtPath('/path/with/suffix.aac', audioOption) // or '.m4a', 'adts' etc.
```
