### ISSUE TITLE
Record audio + Speech To Text API at same time?

### ISSUE THREAD

**Issue by thiennhank9** [jsierles/react-native-audio#200]
Hi guys, how to do 2 above recording audio job at same time.
I'm on task doing STT, but must replay what user said.
But STT doesn't support where to find audio files - which means it can't replay what people have said, so it looks like I'm using cheat here!
Hope any idea to resolve!

**Comment by Noitidart** [comment]
STT is not related to this lib. You can use other APIs like IBM watson - I solved this on iOS, but on Android, the Watson API wasn't working because I had trouble getting the right format as noted here - https://github.com/jsierles/react-native-audio/issues/177#issuecomment-307605468

If you would like help setting up IBM watson on iOS I can help, but if you can please help me with getting IBM Watson working on Android that would be real cool!

**Comment by Noitidart** [comment]
For this, there is now an awesome react-native liv here - https://github.com/wenkesj/react-native-voice - special thanks to @wenkesj

**Comment by TheAlgo** [comment]
Is there any library or way out by which we can record the sound by our android phone and hit that sound to a speech to text api

**Comment by GabrielDvt** [comment]
I really need that as well
