### ISSUE TITLE
Support RN 0.47 issue, not merged with release yet??!

### ISSUE THREAD

**Issue by robboerman2** [jsierles/react-native-audio#219]
react-native-audio :  2.2.0
react-native : 0.49.0
react :  16.0.0
using react-native-sound ? No

On compiling android im still getting this error:

> react-native-audio/android/src/main/java/com/rnim/rn/audio/ReactNativeAudioPackage.java:36: error: method does not override or implement a method from a supertype

### Steps to reproduce

react-native android

I tought that this was already fixed in [pr 199](https://github.com/jsierles/react-native-audio/pull/199), was that not merged with the latest release??!!

**Comment by ufolux** [comment]
@robboerman2  Try this one before they merge the pr，https://github.com/UnPourTous/react-native-audio

**Comment by robboerman2** [comment]
thanks for the responds! 
Sadly im still getting the same error on that git too

**Comment by fredbt** [comment]
Hi there, not sure it's related to this issue, but I'm getting the following error message in a new development machine here:

:react-native-audio:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
.................. /android/src/main/java/com/rnim/rn/audio/ReactNativeAudioPackage.java:13: error: ReactNativeAudioPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ReactNativeAudioPackage implements ReactPackage {
       ^
1 error
:react-native-audio:compileReleaseJavaWithJavac FAILED

This is my config:
react-native-cli: 2.0.1
react-native: 0.46.4
react: "16.0.0-alpha.12"

and I' m using react-native-sound as well:
"react-native-sound": "^0.10.4",

I tried with NPM 5+, which failed, and also with NPM 4+.

It is strange because the error does not happen with other development machines (Linux and IOS) with very similar configurations.

Any ideas?

**Comment by fredbt** [comment]
Ah yeah, forgot to mention my version of "react-native-audio": "^3.2.2".

**Comment by fredbt** [comment]
Apparently NPM was fetching 3.5.0 for my system. When I forced it to use 3.1.0, run-android seemed to work.

**Comment by nerogit** [comment]
@jsierles may i ask why you close this issue?

**Comment by jsierles** [comment]
Sorry, my mistake. Is this still not working? I'll try testing today.

**Comment by jsierles** [comment]
OK, I've tested this and had no problems on 0.47. The issue was fixed by a removal of the offending `createJSModules` method.
