### ISSUE TITLE
Accessing recorded file

### ISSUE THREAD

**Issue by relacsua** [jsierles/react-native-audio#8]
I understand that the 'storage of recorded file into media library' feature is part of your to-do list.
Meanwhile, is there a way to access the recorded file ?

I am intending to upload the recorded file online.

**Comment by jsierles** [comment]
This is not possible yet within this library. Using the react-native-fs library, you could read the file from the documents directory, then post it from javascript. However, this may be slow due to the passing the data over javascript/native bridge.

https://github.com/johanneslumpe/react-native-fs

Here's a library that solves this problem, but only works with files in the image library. Combining the two should get you what you need if the first option is too slow.


https://github.com/kamilkp/react-native-file-transfer

**Comment by MuhammadMuneer** [comment]
@jsierles  Thanks. Will try that out.
